name: new event actions

on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  newevent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Change README.md
        run: |
          time=$(date +%F -d "${{github.event.issue.updated_at}}")
          echo "- [${{ github.event.issue.title}}](${{github.event.issue.html_url}}) $time" >> README.md
      - name: Commit files
        run: |
          git config --local user.name ${{ github.actor }}
          git config --local user.email "qijin.antalpha.com"
          git add README.md
          git commit -m "submit new event (Automated)"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          force: true

  push-telegram:
    runs-on: ubuntu-latest
    needs: newevent
    steps:
      - name: Send to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            NEWS ${{github.event.issue.html_url}}


